import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/navigation/nav'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  profile,
}: Readonly<{
  children: React.ReactNode
  profile: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'px-6 md:px-12 container bg-foreground text-background',
          inter.className
        )}
      >
        <Nav />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  )
}
